import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

export function generateInterviewReport(session) {
  if (!session) return;

  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  let pageNum = 1;

  // Helper to draw header and footer
  const drawHeaderAndFooter = (pdfDoc, page) => {
    // Header
    pdfDoc.setFont('Helvetica', 'bold');
    pdfDoc.setFontSize(18);
    pdfDoc.setTextColor(139, 92, 246); // #8B5CF6
    pdfDoc.text('Prepify Interview Report', 20, 20);

    pdfDoc.setDrawColor(229, 231, 235); // gray-200
    pdfDoc.setLineWidth(0.5);
    pdfDoc.line(20, 23, 190, 23);

    // Footer
    pdfDoc.setFont('Helvetica', 'normal');
    pdfDoc.setFontSize(9);
    pdfDoc.setTextColor(156, 163, 175); // gray-400
    pdfDoc.text('Generated by Prepify', 20, 285);
    pdfDoc.text(`Page ${page}`, 190, 285, { align: 'right' });
  };

  const startNewPage = (pdfDoc) => {
    pdfDoc.addPage();
    pageNum++;
    drawHeaderAndFooter(pdfDoc, pageNum);
  };

  // Draw header/footer on first page
  drawHeaderAndFooter(doc, pageNum);

  // SECTION 1 — Summary box
  const summaryBoxY = 30;
  doc.setFillColor(249, 250, 251); // gray-50
  doc.setDrawColor(243, 244, 246); // gray-100
  doc.setLineWidth(0.3);
  doc.roundedRect(20, summaryBoxY, 170, 42, 3, 3, 'FD');

  // Labels
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(10.5);
  doc.setTextColor(55, 65, 81); // gray-700
  doc.text('Role:', 25, summaryBoxY + 9);
  doc.text('Experience Level:', 25, summaryBoxY + 17);
  doc.text('Date:', 25, summaryBoxY + 25);
  doc.text('Questions Answered:', 25, summaryBoxY + 33);

  // Values
  const formattedDate = session.createdAt ? new Date(session.createdAt).toLocaleDateString() : new Date().toLocaleDateString();
  doc.setFont('Helvetica', 'normal');
  doc.setTextColor(75, 85, 99); // gray-600
  doc.text(String(session.role || 'N/A'), 65, summaryBoxY + 9);
  doc.text(String(session.experienceLevel || 'N/A'), 65, summaryBoxY + 17);
  doc.text(formattedDate, 65, summaryBoxY + 25);
  doc.text(String(session.questions?.length || 0), 65, summaryBoxY + 33);

  // Overall Score (Large Display on Right)
  const score = session.overallScore ?? 0;
  let scoreColor = [239, 68, 68]; // Red
  if (score >= 7) scoreColor = [16, 185, 129]; // Green
  else if (score >= 5) scoreColor = [245, 158, 11]; // Amber

  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(156, 163, 175); // gray-400
  doc.text('OVERALL SCORE', 145, summaryBoxY + 12, { align: 'center' });

  doc.setFontSize(36);
  doc.setTextColor(scoreColor[0], scoreColor[1], scoreColor[2]);
  doc.text(score.toFixed(1), 145, summaryBoxY + 26, { align: 'center' });

  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(156, 163, 175); // gray-400
  doc.text('out of 10', 145, summaryBoxY + 33, { align: 'center' });

  let currentY = summaryBoxY + 42 + 10;

  // SECTION 2 — Category Breakdown (if categoryScores exists)
  if (session.categoryScores && session.categoryScores.length > 0) {
    doc.setFont('Helvetica', 'bold');
    doc.setFontSize(13);
    doc.setTextColor(17, 24, 39); // gray-900
    doc.text('Performance by Category', 20, currentY);
    currentY += 5;

    autoTable(doc, {
      startY: currentY,
      head: [['Category', 'Average Score', 'Questions']],
      body: session.categoryScores.map((c) => [
        c.category,
        `${c.averageScore}/10`,
        c.questionCount,
      ]),
      headStyles: {
        fillColor: [139, 92, 246], // #8B5CF6
        textColor: [255, 255, 255],
        fontStyle: 'bold',
      },
      alternateRowStyles: {
        fillColor: [249, 250, 251],
      },
      theme: 'striped',
      margin: { left: 20, right: 20 },
      styles: {
        font: 'Helvetica',
        fontSize: 9.5,
      },
    });

    currentY = doc.lastAutoTable.finalY + 10;
  }

  // SECTION 3 — Question-by-Question Breakdown
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(13);
  doc.setTextColor(17, 24, 39); // gray-900
  doc.text('Detailed Question Breakdown', 20, currentY);
  currentY += 8;

  session.questions?.forEach((q, index) => {
    const ans = session.answers?.find((a) => a.questionId === q.id) || {
      answer: 'No answer provided',
      score: 0,
      strengths: '',
      improvements: '',
      idealAnswerHints: '',
    };

    // A4 height is 297mm. Bottom margin is 25mm. Safe limit is 272mm.
    // Check if we need to start a new page before drawing the question header
    if (currentY > 235) {
      startNewPage(doc);
      currentY = 30;
    }

    // Question Header: Question X [Category] [Difficulty] [Source]
    doc.setFont('Helvetica', 'bold');
    doc.setFontSize(10.5);
    doc.setTextColor(55, 65, 81); // gray-700
    doc.text(`Question ${index + 1}`, 20, currentY);

    let tagText = `[Category: ${q.category || 'General'}]  [Difficulty: ${q.difficulty || 'Medium'}]`;
    if (q.source === 'resume') {
      tagText += `  [📄 Resume-Tailored]`;
    }
    doc.setFont('Helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(156, 163, 175); // gray-400
    doc.text(tagText, 45, currentY);
    currentY += 5;

    // Question Text
    doc.setFont('Helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(17, 24, 39); // gray-900
    const splitQuestionText = doc.splitTextToSize(q.question || '', 170);
    doc.text(splitQuestionText, 20, currentY);
    currentY += (splitQuestionText.length * 4.2) + 4;

    // Answer Text Box
    if (currentY > 240) {
      startNewPage(doc);
      currentY = 30;
    }

    doc.setFont('Helvetica', 'normal');
    doc.setFontSize(9.5);
    doc.setTextColor(55, 65, 81); // gray-700

    const answerStr = `Answer: ${ans.answer || 'No answer provided'}`;
    const splitAnswerText = doc.splitTextToSize(answerStr, 160);
    const boxHeight = (splitAnswerText.length * 4.5) + 6;

    doc.setFillColor(249, 250, 251); // gray-50
    doc.setDrawColor(243, 244, 246); // gray-100
    doc.setLineWidth(0.3);
    doc.roundedRect(20, currentY, 170, boxHeight, 2, 2, 'FD');
    doc.text(splitAnswerText, 25, currentY + 5.5);
    currentY += boxHeight + 4;

    // Score
    if (currentY > 255) {
      startNewPage(doc);
      currentY = 30;
    }

    const qScore = ans.score ?? 0;
    let qScoreColor = [239, 68, 68]; // Red
    if (qScore >= 7) qScoreColor = [16, 185, 129]; // Green
    else if (qScore >= 5) qScoreColor = [245, 158, 11]; // Amber

    doc.setFont('Helvetica', 'bold');
    doc.setFontSize(9.5);
    doc.setTextColor(17, 24, 39); // gray-900
    doc.text('Score: ', 20, currentY);

    doc.setTextColor(qScoreColor[0], qScoreColor[1], qScoreColor[2]);
    doc.text(`${qScore}/10`, 32, currentY);
    currentY += 5;

    // Strengths
    if (ans.strengths && ans.strengths.trim()) {
      if (currentY > 255) {
        startNewPage(doc);
        currentY = 30;
      }
      doc.setFont('Helvetica', 'bold');
      doc.setFontSize(9.5);
      doc.setTextColor(16, 185, 129); // green-500
      doc.text('Strengths:', 20, currentY);
      currentY += 4.5;

      doc.setFont('Helvetica', 'normal');
      doc.setTextColor(55, 65, 81); // gray-700

      const strengthsList = String(ans.strengths)
        .split(';')
        .map((s) => s.trim())
        .filter(Boolean);

      strengthsList.forEach((strength) => {
        if (currentY > 260) {
          startNewPage(doc);
          currentY = 30;
        }
        const splitStrengthText = doc.splitTextToSize(`• ${strength}`, 165);
        doc.text(splitStrengthText, 22, currentY);
        currentY += (splitStrengthText.length * 4) + 1;
      });
      currentY += 1.5;
    }

    // Improvements
    if (ans.improvements && ans.improvements.trim()) {
      if (currentY > 255) {
        startNewPage(doc);
        currentY = 30;
      }
      doc.setFont('Helvetica', 'bold');
      doc.setFontSize(9.5);
      doc.setTextColor(245, 158, 11); // amber-500
      doc.text('Areas for Improvement:', 20, currentY);
      currentY += 4.5;

      doc.setFont('Helvetica', 'normal');
      doc.setTextColor(55, 65, 81); // gray-700

      const improvementsList = String(ans.improvements)
        .split(';')
        .map((s) => s.trim())
        .filter(Boolean);

      improvementsList.forEach((imp) => {
        if (currentY > 260) {
          startNewPage(doc);
          currentY = 30;
        }
        const splitImpText = doc.splitTextToSize(`• ${imp}`, 165);
        doc.text(splitImpText, 22, currentY);
        currentY += (splitImpText.length * 4) + 1;
      });
      currentY += 1.5;
    }

    // Ideal Answer Hints (if present)
    if (ans.idealAnswerHints && ans.idealAnswerHints.trim()) {
      if (currentY > 245) {
        startNewPage(doc);
        currentY = 30;
      }
      doc.setFont('Helvetica', 'bold');
      doc.setFontSize(9.5);
      doc.setTextColor(6, 182, 212); // cyan-500
      doc.text('Ideal Answer Hints:', 20, currentY);
      currentY += 4.5;

      doc.setFont('Helvetica', 'italic');
      doc.setTextColor(107, 114, 128); // gray-500
      const splitIdealText = doc.splitTextToSize(ans.idealAnswerHints, 165);
      doc.text(splitIdealText, 22, currentY);
      currentY += (splitIdealText.length * 4) + 3;
    }

    // Gap between questions
    currentY += 7;
  });

  // Save PDF
  const cleanRole = String(session.role || 'Interview')
    .replace(/[^a-zA-Z0-9 ]/g, '')
    .trim()
    .replace(/\s+/g, '-');
  const cleanDate = formattedDate.replace(/[^a-zA-Z0-9]/g, '-');
  const filename = `Prepify-Report-${cleanRole}-${cleanDate}.pdf`;

  doc.save(filename);
}
